---
# tasks file for rpm_install

# cannot use yum to install rpm because it will never upgrade (https://github.com/ansible/ansible-modules-core/issues/4529)
- name: Install rpm
  command: "rpm {{ (rpm_nosignature) | ternary('--nosignature','') }} {{ (rpm_force_install) | ternary('--force','') }} -U {{ rpm_path }}"
  args:
    warn: no

