- name: restart crond
  service: name=crond state=restarted
- name: restart auditd
  service: name=auditd state=restarted use=service
- name: restart sshd
  service: name=sshd state=restarted
- name: restart postfix
  service: name=postfix state=restarted
- name: newaliases
  command: newaliases
  notify: restart postfix