---
- name: Download Kapacitor
  when: kapacitor_download
  get_url:
    url: "https://dl.influxdata.com/kapacitor/releases/kapacitor-{{ kapacitor_version }}.x86_64.rpm"
    dest: /tmp
    mode: 0755
  tags: [ download ]

- name: install Kapacitor RPM from a local file
  yum:
    name: "/tmp/kapacitor-{{ kapacitor_version }}.x86_64.rpm"
    state: present
  tags: [ install, yum ]
