---
grafana_download: true
grafana_version: 6.1.1
grafana_app_mode: production
grafana_filename: "grafana-{{ grafana_version }}-1.x86_64.rpm"
grafana_dest: /tmp

grafana_root_url: 'http://localhost:3000'
grafana_admin_user: "admin"
grafana_admin_password: "admin"

grafana_log_mode: 'console file'
grafana_log_level: 'info'

grafana_external_image_storage_provider: ''
grafana_external_image_storage_s3_bucket_url: ''

grafana_smtp_enabled: false
grafana_smtp_display_name: "Grafana"
grafana_smtp_host: "localhost:25"
