---
# tasks file for nifi_nars

- name: Ensure required directories exist
  file:
    path: "{{ nifi_nars_base_dir }}"
    state: directory
    owner: "{{ nifi_nars_user }}"
    group: "{{ nifi_nars_group }}"
    mode: 0755

- name: Ensure symlink
  file: src="{{ nifi_nars_base_dir }}/{{ nifi_nars_dir }}" dest="{{ nifi_nars_symlink }}" state=link
  notify:
    - restart nifi

- name: Ensure nars are configured in nifi.properties
  lineinfile:
    dest: "{{ nifi_conf_dir }}/nifi.properties"
    state: present
    regexp: "^nifi.nar.library.directory.{{ nifi_nars_id }}="
    line: "nifi.nar.library.directory.{{ nifi_nars_id }}={{ nifi_nars_symlink }}"
    insertafter: "^nifi.nar.library.directory="
  notify:
    - restart nifi
  when: nifi_nars_id is defined

